<a href="https://colab.research.google.com/github/Nikhil5566/EDA-Repo/blob/main/Hugging_face_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [5]:
from huggingface_hub import notebook_login

notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [14]:
df = pd.read_csv("hf://datasets/fka/awesome-chatgpt-prompts/prompts.csv")
df.head(11)

,act,prompt
0,An Ethereum Developer,Imagine you are an experienced Ethereum develo...
1,SEO Prompt,"Using WebPilot, create an outline for an artic..."
2,Linux Terminal,I want you to act as a linux terminal. I will ...
3,English Translator and Improver,"I want you to act as an English translator, sp..."
4,`position` Interviewer,I want you to act as an interviewer. I will be...
5,JavaScript Console,I want you to act as a javascript console. I w...
6,Excel Sheet,I want you to act as a text based excel. you'l...
7,English Pronunciation Helper,I want you to act as an English pronunciation ...
8,Spoken English Teacher and Improver,I want you to act as a spoken English teacher ...
9,Travel Guide,I want you to act as a travel guide. I will wr...
10,Plagiarism Checker,I want you to act as a plagiarism checker. I w...

In [15]:
df.tail(11)

,act,prompt
192,Architect Guide for Programmers,"You are the ""Architect Guide,"" specialized in ..."
193,ChatGPT prompt generator,Let's refine the process of creating high-qual...
194,Children's Book Creator,I want you to act as a Children's Book Creator...
195,Tech-Challenged Customer,Pretend to be a non-tech-savvy customer callin...
196,Creative Branding Strategist,"You are a creative branding strategist, specia..."
197,Book Summarizer,I want you to act as a book summarizer. Provid...
198,study planner,I want you to act as an advanced study plan ge...
199,SEO specialist,Contributed by [@suhailroushan13](https://gith...
200,Note-Taking Assistant,I want you to act as a note-taking assistant f...
201,Nutritionist,Act as a nutritionist and create a healthy rec...
202,Yes or No answer,I want you to reply to questions. You reply on...

In [16]:
df.shape

(203, 2)

In [17]:
df.columns

Index(['act', 'prompt'], dtype='object')

In [18]:
df.dtypes

act       object
prompt    object
dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   act     203 non-null    object
 1   prompt  203 non-null    object
dtypes: object(2)
memory usage: 3.3+ KB

In [20]:
df.describe(include = 'all')

               act                                             prompt
count          203                                                203
unique         201                                                203
top     Life Coach  Imagine you are an experienced Ethereum develo...
freq             2                                                  1

In [21]:
df.isnull().sum()

act       0
prompt    0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)