<a href="https://colab.research.google.com/github/Nikhil5566/EDA-Repo/blob/main/Job_Market_Dataset_Insights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('job_market_unemployment_trends.csv')
df.head()

,id,date,location,unemployment_rate,job_postings,in_demand_skills,average_age,college_degree_percentage
0,1,2023-10-07,Houston,6.8,4894,"Agile Methodologies, Project Management",44,74
1,2,2025-05-24,Washington,11.1,2695,"Data Analysis, UX/UI Design, Digital Marketing",50,87
2,3,2024-09-28,Chicago,7.3,1174,"Agile Methodologies, Digital Marketing, Machin...",48,54
3,4,2024-12-28,Indianapolis,11.2,3708,"Cloud Computing, UX/UI Design",36,75
4,5,2023-09-10,New York,13.7,268,"SQL, Machine Learning, Python, Project Managem...",41,75

# Basic Aggregation

1. What is the overall average unemployment rate across all locations in the dataset as of July 29, 2025? How does this compare to the total number of job postings recorded?

2. Calculate the total number of job postings and the overall average college degree percentage across all entries. What might this indicate about the workforce's educational background?

3. What is the overall median unemployment rate across all locations? How does it differ from the mean, and what might this suggest about the data distribution?

In [23]:
# Calculate total job postings and average college degree percentage
print('Total number of job postings recorded: ', df['job_postings'].sum())
print('The overall average unemployment rate across all locations in the dataset', df['college_degree_percentage'].mean())

Total number of job postings recorded:  2495041
The overall average unemployment rate across all locations in the dataset 60.608

In [13]:
print('The total number of job posted:', df['job_postings'].sum())
print('The overall average college degree percentage across all entries:', df['college_degree_percentage'].mean())

The total number of job posted: 2495041
The overall average college degree percentage across all entries: 60.608

In [37]:
# Calculate median and mean unemployment rate
print('The overall mean unemployment rate across all locations:', df['unemployment_rate'].mean())
print('The overall median unemployment rate across all locations:',df['unemployment_rate'].median())

The overall mean unemployment rate across all locations: 8.629700000000001
The overall median unemployment rate across all locations: 8.8

# Group Aggregation

1. Compare the average unemployment rate between locations with an average age above 40 and those below 40. Which group shows a higher rate, and what could be a potential reason?

2. Analyze the average number of job postings for locations where the college degree percentage is above 70% versus those below 70%. What trends can you identify regarding education and job opportunities?

3. Compare the average unemployment rate in 2024 to that in 2025 (up to July 29, 2025). Which year has a lower rate, and what might this suggest about recent job market trends?

In [44]:
print('The average unemployment rate between locations with an average age above 40 and those below 40:', df[df['average_age'] > 40].groupby('location')['unemployment_rate'].mean())
print('The average unemployment rate between locations with an average age above 40 :', df[df['average_age'] > 40].groupby('location')['unemployment_rate'].mean())

The average unemployment rate between locations with an average age above 40 and those below 40: location
Austin            9.672222
Charlotte         8.757143
Chicago           8.468182
Columbus          9.126316
Dallas            8.573077
Denver            6.900000
Fort Worth        9.072222
Houston           8.692308
Indianapolis      6.880000
Jacksonville      9.069231
Los Angeles      10.130000
New York          9.946667
Philadelphia      7.777778
Phoenix           7.525000
San Antonio       8.669231
San Diego         9.730769
San Francisco     8.570000
San Jose          8.790000
Seattle           8.528571
Washington        8.345000
Name: unemployment_rate, dtype: float64
The average unemployment rate between locations with an average age above 40 : location
Austin            9.672222
Charlotte         8.757143
Chicago           8.468182
Columbus          9.126316
Dallas            8.573077
Denver            6.900000
Fort Worth        9.072222
Houston           8.692308
Indianapolis      6.880000
Jacksonville      9.069231
Los Angeles      10.130000
New York          9.946667
Philadelphia      7.777778
Phoenix           7.525000
San Antonio       8.669231
San Diego         9.730769
San Francisco     8.570000
San Jose          8.790000
Seattle           8.528571
Washington        8.345000
Name: unemployment_rate, dtype: float64

In [51]:
print('The average number of job postings for locations where the college degree percentage above 70% :', df[df['college_degree_percentage'] > 70].groupby('location')['job_postings'].mean())
print('The average number of job postings for locations where the college degree percentage below 70% :', df[df['college_degree_percentage'] <= 70].groupby('location')['job_postings'].mean())

The average number of job postings for locations where the college degree percentage above 70% : location
Austin           3107.437500
Charlotte        2697.789474
Chicago          2235.875000
Columbus         2403.041667
Dallas           2719.681818
Denver           3179.272727
Fort Worth       2610.000000
Houston          3240.600000
Indianapolis     2495.733333
Jacksonville     2623.428571
Los Angeles      1575.214286
New York         2208.523810
Philadelphia     2458.470588
Phoenix          2543.000000
San Antonio      2699.333333
San Diego        2493.181818
San Francisco    2046.428571
San Jose         2622.866667
Seattle          2760.450000
Washington       3207.750000
Name: job_postings, dtype: float64
The average number of job postings for locations where the college degree percentage below 70% : location
Austin           2652.647059
Charlotte        2277.965517
Chicago          2842.750000
Columbus         2455.137931
Dallas           2129.800000
Denver           2108.000000
Fort Worth       2659.694444
Houston          2496.535714
Indianapolis     2326.100000
Jacksonville     2587.193548
Los Angeles      2500.730769
New York         2119.173913
Philadelphia     2212.870968
Phoenix          2618.000000
San Antonio      2421.515152
San Diego        2402.294118
San Francisco    2741.375000
San Jose         2769.921053
Seattle          2093.761905
Washington       2471.945946
Name: job_postings, dtype: float64

In [62]:
df['date'] = pd.to_datetime(df['date'])

# Filter by year
data_2024 = df[df['date'].dt.year == 2024]
data_2025 = df[df['date'].dt.year == 2025]

avg_unemployment_2024 = data_2024['unemployment_rate'].mean()
avg_unemployment_2025 = data_2025['unemployment_rate'].mean()

print(f"Average unemployment rate in 2024: {avg_unemployment_2024:.2f}%")
print(f"Average unemployment rate in 2025 (up to July 29): {avg_unemployment_2025:.2f}%")
print(f"Insight: 2025 ({avg_unemployment_2025:.2f}%) shows a lower rate than 2024 ({avg_unemployment_2024:.2f}%), possibly indicating an improving job market as of mid-2025.")

Average unemployment rate in 2024: 8.71%
Average unemployment rate in 2025 (up to July 29): 8.44%
Insight: 2025 (8.44%) shows a lower rate than 2024 (8.71%), possibly indicating an improving job market as of mid-2025.

# Ranking / Top-N

1. Identify the top 5 locations with the highest average unemployment rate. What are their average job postings, and how might this guide local employment policies?

2. Rank the locations by the total number of job postings and list the top 3. What are the most frequent in-demand skills among these locations?

3. Find the top 5 locations with the highest average college degree percentage. How do their average ages compare to the overall average age across all locations?

In [74]:
print('The top 5 locations with the highest average unemployment rate:', df.groupby('location')['unemployment_rate'].mean().nlargest(5, ))
print('The top 5 locations with the highest average unemployment rate. What are their average job postings:', df.groupby('location')['job_postings'].mean().nlargest(5, ))

The top 5 locations with the highest average unemployment rate: location
San Diego       9.786667
Austin          9.240000
Jacksonville    9.157778
Los Angeles     9.055000
Fort Worth      9.004000
Name: unemployment_rate, dtype: float64
The top 5 locations with the highest average unemployment rate. What are their average job postings: location
Austin        2798.180000
Washington    2730.122807
San Jose      2728.301887
Houston       2692.342105
Fort Worth    2645.780000
Name: job_postings, dtype: float64

In [98]:
print('The locations by the total number of job postings and list the top 3:', df.groupby('location')['job_postings'].sum().nlargest(3))
skill = df.groupby('location')['in_demand_skills'].value_counts()
most_frequent_skill = skill.nlargest(5)
display(most_frequent_skill)

The locations by the total number of job postings and list the top 3: location
Washington     155617
San Antonio    152792
Chicago        144629
Name: job_postings, dtype: int64

location  in_demand_skills
Chicago   Customer Service, SQL              2
Columbus  Python, Cybersecurity              2
Dallas    Customer Service, UX/UI Design     2
Houston   Cloud Computing, Sales             2
          Data Analysis, Customer Service    2
Name: count, dtype: int64